export {
  getAuthorPreviewIndex,
  type AuthorPreviewConceptEntry,
  type AuthorPreviewIndex,
  type AuthorPreviewTrackEntry,
} from "./author-preview";

export {
  conceptCatalogEntrySchema,
  conceptCatalogSchema,
  conceptCollectionSchema,
  conceptPageFrameworkSchema,
  conceptRecordSchema,
  conceptRegistryEntrySchema,
  conceptRegistrySchema,
  conceptRichContentSchema,
  conceptSchema,
  normalizedConceptCollectionSchema,
  simulationKinds,
  type ConceptAccent,
  type ConceptContent,
  type ConceptContentFile,
  type ConceptControl,
  type ConceptChallengeCheck,
  type ConceptChallengeItem,
  type ConceptChallengeMode,
  type ConceptChallengeSetup,
  type ConceptDifficulty,
  type ConceptEquation,
  type ConceptGraph,
  type GuidedCollectionFormat,
  type GuidedCollectionId,
  type LearningPathEntryDiagnosticMetadata,
  type LearningPathEntryDiagnosticProbeMetadata,
  type GuidedCollectionMetadata,
  type GuidedCollectionStepMetadata,
  type GuidedCollectionSurfaceCompletionMode,
  type GuidedCollectionSurfaceKind,
  type ConceptId,
  type ConceptMetadata,
  type ConceptNoticePrompt,
  type ConceptNoticePromptConditions,
  type ConceptNoticePromptConfig,
  type ConceptNoticePromptType,
  type ConceptPageFramework,
  type ConceptPageFeaturedSetup,
  type ConceptPageSectionConfig,
  type ConceptPageSectionId,
  type ConceptPredictionChoice,
  type ConceptPredictionItem,
  type ConceptPredictionMode,
  type ConceptQuickTest,
  type ConceptQuickTestChoice,
  type ConceptQuickTestMode,
  type ConceptQuickTestQuestion,
  type ConceptQuickTestQuestionType,
  type ConceptQuickTestShowMeAction,
  type ConceptQuickTestTemplate,
  type ConceptRecommendation,
  type ConceptRichContent,
  type ConceptSummary,
  type ConceptSubject,
  type ConceptStatus,
  type ConceptWorkedExample,
  type ConceptWorkedExampleAction,
  type ConceptWorkedExamples,
  type ConceptWorkedExampleStep,
  type ConceptWorkedExampleVariable,
  type ConceptSection,
  type ConceptSlug,
  type ConceptTopic,
  type ConceptVariableLink,
  type SimulationKind,
  type StarterTrackCheckpointMetadata,
  type StarterTrackId,
  type StarterTrackMetadata,
  type SubjectMetadata,
  type TopicLandingGroupMetadata,
  type TopicLandingMetadata,
  type TestPackMetadata,
  type TestPackQuestionKind,
  type TestPackQuestionMetadata,
  guidedCollectionCatalogEntrySchema,
  guidedCollectionCatalogSchema,
  learningPathEntryDiagnosticProbeSchema,
  learningPathEntryDiagnosticSchema,
  testPackCatalogEntrySchema,
  testPackCatalogSchema,
  starterTrackCheckpointSchema,
  starterTrackCatalogEntrySchema,
  starterTrackCatalogSchema,
  subjectCatalogEntrySchema,
  subjectCatalogSchema,
  topicLandingCatalogEntrySchema,
  topicLandingCatalogSchema,
} from "./schema";

export {
  resolveLearningPathEntryDiagnostic,
  type ResolvedLearningPathEntryDiagnostic,
  type ResolvedLearningPathEntryDiagnosticChallengeProbe,
  type ResolvedLearningPathEntryDiagnosticProbe,
  type ResolvedLearningPathEntryDiagnosticQuickTestProbe,
} from "./entry-diagnostics";

export {
  getChallengeCatalogEntries,
  getChallengeCueLabels,
  getChallengeDepth,
  getChallengeItemSignals,
  getChallengeRequirementLabels,
  getChallengeTargetLabels,
  normalizeChallengeModeAuthoring,
  type ChallengeCatalogEntry,
  type ChallengeDepth,
  type ChallengeItemSignals,
} from "./challenges";

export {
  type ConceptFallbackAttempt,
  type ContentQaStatus as ConceptQaStatus,
  type ContentReviewStatus as ConceptReviewStatus,
  type ConceptVariantCandidateMetadata,
  type ConceptVariantManifest,
  type ConceptVariantManifestEntry,
  type ConceptVariantSummary,
  type ResolvedConceptContentMetadata,
} from "./variant-types";

export {
  resolveConceptVariantSelection,
  type ResolvedConceptVariantSelection,
} from "./variant-resolution";

export {
  buildChallengeTrackBrowserHref,
  getChallengeDiscoveryIndex,
  getChallengeDiscoveryMetrics,
  resolveChallengeTrackCtaTargets,
  type ChallengeDiscoveryConceptSummary,
  type ChallengeDiscoveryEntry,
  type ChallengeDiscoveryIndex,
  type ChallengeDiscoveryTrackCtaTargets,
  type ChallengeDiscoveryTopicSummary,
  type ChallengeDiscoveryTrackSummary,
} from "./challenge-discovery";

export {
  getConceptPageSectionConfig,
  resolveConceptPageSections,
  type ConceptPageSectionSlot,
  type ResolvedConceptPageSection,
} from "./concept-page-framework";

export {
  conceptPageV2LessonHashId,
  conceptPageV2StepHashPrefix,
  getConceptPageV2StepHashId,
  resolveConceptPageV2,
  resolveConceptPageV2StepIdFromHash,
  resolveConceptPageV2StepIdFromLegacyPhase,
  type ResolvedConceptPageV2,
  type ResolvedConceptPageV2EquationSnapshot,
  type ResolvedConceptPageV2InlineCheck,
  type ResolvedConceptPageV2RevealItem,
  type ResolvedConceptPageV2Step,
  type ResolvedConceptPageV2WrapUp,
} from "./concept-page-v2";

export {
  conceptLearningPhaseIds,
  conceptLearningPhaseQueryParam,
  getDefaultConceptLearningPhaseId,
  parseConceptLearningPhaseId,
  resolveInitialConceptLearningPhaseId,
  resolveConceptLearningPhases,
  type ConceptLearningPhaseDefinition,
  type ConceptLearningPhaseId,
  type ResolvedConceptLearningPhase,
} from "./concept-learning-phases";

export {
  buildConceptRegistry,
  getAllConceptMetadata,
  getAllConcepts,
  getConceptBySlug,
  getConceptById,
  getConceptCatalogFilePath,
  getConceptCatalogMetrics,
  getConceptFilePath,
  getConceptLastModified,
  getConceptMetadataById,
  getConceptMetadataBySlug,
  getPublishedConceptMetadata,
  getConceptRegistry,
  getConceptRegistryIndex,
  getConceptSlugs,
  getConceptSummaries,
  getConceptSubjects,
  getConceptTopics,
  getConceptsBySubtopic,
  getConceptsByTopic,
  validateConceptBundle,
  validateConceptCatalogMetadata,
  validateConceptRegistry,
  type ConceptRegistry,
} from "./loaders";

export {
  getReadNextRecommendations,
  resolveReadNextFromRegistry,
  type ReadNextRecommendation,
  type ReadNextReasonKind,
} from "./read-next";

export {
  getGuidedCollectionBySlug,
  getGuidedCollectionCatalogFilePath,
  getGuidedCollectionCatalogLastModified,
  getGuidedCollectionCatalogMetrics,
  getGuidedCollections,
  validateGuidedCollectionCatalog,
  type GuidedCollectionEntryDiagnosticSummary,
  type GuidedCollectionChallengeStepSummary,
  type GuidedCollectionConceptStepSummary,
  type GuidedCollectionStepSummary,
  type GuidedCollectionSummary,
  type GuidedCollectionSurfaceStepSummary,
  type GuidedCollectionTrackStepSummary,
} from "./guided-collections";

export {
  getRecommendedGoalPathBySlug,
  getRecommendedGoalPathCatalogFilePath,
  getRecommendedGoalPaths,
  getRecommendedGoalPathsForTopic,
  recommendedGoalPathCatalogEntrySchema,
  recommendedGoalPathCatalogSchema,
  recommendedGoalPathStepSchema,
  validateRecommendedGoalPathCatalog,
  type RecommendedGoalPathConceptStepSummary,
  type RecommendedGoalPathGoalKind,
  type RecommendedGoalPathGuidedCollectionStepSummary,
  type RecommendedGoalPathMetadata,
  type RecommendedGoalPathStepMetadata,
  type RecommendedGoalPathStepSummary,
  type RecommendedGoalPathSummary,
  type RecommendedGoalPathTopicStepSummary,
  type RecommendedGoalPathTrackStepSummary,
} from "./recommended-goal-paths";

export {
  getStarterTrackBySlug,
  getStarterTrackCatalogFilePath,
  getStarterTrackCatalogLastModified,
  getStarterTrackCatalogMetrics,
  getStarterTrackDiscoveryHighlights,
  getStarterTrackMembershipsForConcept,
  getStarterTracks,
  validateStarterTrackCatalog,
  type StarterTrackEntryDiagnosticSummary,
  type StarterTrackCheckpointSummary,
  type StarterTrackConceptMembership,
  type StarterTrackSummary,
} from "./starter-tracks";

export {
  getLegacyTopicDiscoverySlugs,
  getTopicDiscoverySummaries,
  getTopicDiscoverySlugs,
  getTopicDiscoverySummaryBySlug,
  getTopicDiscoverySummaryForConceptSlug,
  getTopicLastModified,
  getTopicPath,
  getTopicSlug,
  getTopicTitle,
  type TopicDiscoverySummary,
  type TopicDiscoveryGroupSummary,
  type TopicDiscoveryRelatedTopicSummary,
} from "./topics";

export {
  getSubjectCatalogFilePath,
  getSubjectCatalogLastModified,
  getSubjectDiscoverySummaries,
  getSubjectDiscoverySlugs,
  getSubjectDiscoverySummaryBySlug,
  getSubjectDiscoverySummaryByTitle,
  getSubjectDiscoverySummaryForConceptSlug,
  getSubjectDiscoverySummaryForTopicSlug,
  getSubjectPath,
  validateSubjectCatalog,
  type SubjectDiscoverySummary,
} from "./subjects";

export {
  buildExpandedSubjectSpotlights,
  type ExpandedSubjectSpotlight,
} from "./discovery-surfacing";

export {
  buildStartLearningSubjectChoices,
  getStartLearningRecommendationSet,
  startLearningCommitmentOptions,
  startLearningConfidenceOptions,
  startLearningInterestNotSure,
  type StartLearningCommitment,
  type StartLearningConfidence,
  type StartLearningInterest,
  type StartLearningRecommendation,
  type StartLearningRecommendationKind,
  type StartLearningRecommendationSet,
  type StartLearningSubjectChoice,
} from "./start-learning";

export {
  buildConceptSearchMetadataBySlug,
  buildSiteSearchIndex,
  normalizeSiteSearchText,
  searchSiteIndex,
  siteSearchMatchStrengths,
  siteSearchResultKinds,
  type SiteSearchConceptMetadata,
  type SiteSearchConceptMetadataBySlug,
  type SiteSearchEntry,
  type SiteSearchIndex,
  type SiteSearchIndexInput,
  type SiteSearchMatch,
  type SiteSearchMatchStrength,
  type SiteSearchResultKind,
} from "./search";
