export const ACHIEVEMENT_REWARD_KEY = "premium-first-month-25-off";
export const ACHIEVEMENT_REWARD_EXPIRY_DAYS = 30;
export const ACHIEVEMENT_REWARD_DISCOUNT_PERCENT = 25;
export const ACHIEVEMENT_STUDY_HEARTBEAT_SECONDS = 15;
export const ACHIEVEMENT_VISIT_ACTIVE_SECONDS = 45;
export const ACHIEVEMENT_VISIT_INTERACTION_COUNT = 2;
export const ACHIEVEMENT_MIN_VISIBLE_HOURS_PROGRESS = 0.05;
export const ACHIEVEMENT_REWARD_CHALLENGE_TARGET = 30;
export const ACHIEVEMENT_REWARD_STUDY_HOURS_TARGET = 10;
export const ACHIEVEMENT_REWARD_STUDY_SECONDS_TARGET =
  ACHIEVEMENT_REWARD_STUDY_HOURS_TARGET * 60 * 60;
